akash-akya/vix

- README.md
- c_src/vips_image.c
- c_src/vips_image.h
- c_src/vix.c
- lib/vix/nif.ex
- lib/vix/vips/image.ex
- test/vix/vips/image_test.exs
- test/vix/vips/operation_test.exs
Fixes https://github.com/akash-akya/vix/issues/2
> Support vips image headers

- README.md
- c_src/vips_image.c
- c_src/vips_image.h
- c_src/vix.c
- lib/vix/nif.ex
- lib/vix/vips/image.ex
- lib/vix/vips/operation.ex
* remove mutable operations
* add `vips_image_copy_memory`
* update documentation
* remove required, deprecated arguments
> Remove mutable operations & other changes

- c_src/vips_image.c
- c_src/vips_image.h
- c_src/vix.c
- lib/vix/g_object/double.ex
- lib/vix/nif.ex
- lib/vix/vips/image.ex
- test/vix/vips/image_test.exs
Fixes https://github.com/akash-akya/vix/issues/5
> Add vips_image_new_from_image

- c_src/Makefile
> Append to existing compile flags

- .github/workflows/elixir.yaml
- c_src/g_object/g_object.c
- c_src/g_object/g_param_spec.c
- c_src/g_object/g_type.c
- c_src/g_object/g_value.c
- c_src/utils.c
- c_src/utils.h
- c_src/vips_image.c
- c_src/vips_operation.c
- c_src/vips_operation.h
- lib/vix/g_object/string.ex
- lib/vix/vips/enum.ex
- lib/vix/vips/flag.ex
- lib/vix/vips/image.ex
- lib/vix/vips/operation.ex
- test/vix/nif_test.exs
- test/vix/vips/array_double_test.exs
- test/vix/vips/array_int_test.exs
- test/vix/vips/image_test.exs
- test/vix/vips/operation_test.exs
* fix required output values order
* use binary strings instead of charlist
* update GitHub actions
> Fix required output values order and misc changes

- c_src/g_object/g_object.c
- c_src/g_object/g_type.c
- c_src/g_object/g_value.c
- c_src/utils.c
- c_src/utils.h
- c_src/vips_boxed.c
- c_src/vips_image.c
- c_src/vips_operation.c
- lib/vix/vips/operation.ex
- test/vix/vips/operation_test.exs
* return vips operation error from NIF
* refactor `VixResult` handling
> Return vips operation error from NIF

- c_src/vips_boxed.c
- c_src/vips_boxed.h
- c_src/vips_image.c
- c_src/vix.c
- lib/vix/g_object/g_param_spec.ex
- lib/vix/nif.ex
- lib/vix/type.ex
- lib/vix/vips/blob.ex
- lib/vix/vips/image.ex
- lib/vix/vips/operation.ex
- lib/vix/vips/ref_string.ex
- test/vix/vips/blob_test.exs
- test/vix/vips/image_test.exs
- test/vix/vips/ref_string_test.exs
- test/vix/vips/type_test.exs
> Add support for VipsBlob & VipsRefString

- c_src/Makefile
Fixes https://github.com/akash-akya/vix/issues/19
> Remove arch compiler flag

- c_src/vips_interpolate.c
- c_src/vips_interpolate.h
- c_src/vix.c
- lib/vix/nif.ex
- lib/vix/type.ex
- lib/vix/vips/image.ex
- lib/vix/vips/interpolate.ex
- lib/vix/vips/operation.ex
- test/vix/vips/interpolate_test.exs
- test/vix/vips/type_test.exs
Closes https://github.com/akash-akya/vix/issues/23
> Add support for vips-interpolate

- c_src/g_object/g_value.c
- c_src/g_object/g_value.h
- c_src/vips_image.c
- c_src/vips_image.h
- c_src/vix.c
- lib/vix/nif.ex
- lib/vix/vips/image.ex
- lib/vix/vips/mutable_image.ex
- test/vix/vips/image_test.exs
- test/vix/vips/mutable_image_test.exs
> Support mutable image

- c_src/vips_operation.c
- lib/vix/vips/image.ex
Related to https://github.com/akash-akya/vix/issues/25
> Include foreign operations

- README.md
- c_src/utils.h
> Make error logging configurable and disable it by default

- c_src/g_object/g_value.c
- c_src/utils.c
- c_src/utils.h
> Handle null g_value

- .github/workflows/ci.yaml
See https://github.com/libvips/libvips/issues/3024
> Fix libvips version in gh action to v8.13.0

- lib/vix/vips/enum.ex
- lib/vix/vips/flag.ex
Found via `mix credo --strict`.
Let me know if you want to add Credo to the GitHub CI job and resolve all issues raised by Credo.
> Resolve no unused return values for Enum functions

- lib/vix/vips/image.ex
- test/vix/vips/access_test.exs
* removed support for `:all` 
* support for keyword list as access value 
* Integer value always returns single column or row or band instead of range value (`0..value`)
* changes to parameter validation
> Add support for keyword list for Image access

- lib/vix/vips/operation_helper.ex
- test/vix/vips/operation_test.exs
Fixes https://github.com/kipcole9/image/issues/25 & https://github.com/akash-akya/vix/issues/82
> Skip unsupported additional arguments

- lib/vix/vips/image.ex
> Handle null attributes

- .github/workflows/precompile.yaml
OTP v26 changed NIF version from 2.16 to 2.17
Fixes #117
> Precompile binaries for NIF version 2.17

- DEVELOPMENT.md
- lib/vix/vips/operation.ex
- lib/vix/vips/operation_helper.ex
> Do not use reserved word as variable name 

- .github/workflows/ci.yaml
- lib/vix/vips/image.ex
> Fix logger macro deprecation warning

- livebooks/picture-language.livemd
> Fixed broken link on LiveBook notebook

- README.md
- c_src/utils.c
- c_src/utils.h
- c_src/vix.c
- lib/vix/nif.ex
- mix.exs
- test/vix/vips/access_test.exs
- test/vix/vips/image_test.exs
Fixes https://github.com/elixir-image/image/discussions/161
> Refactor NIF/libvips logging: disable logging by default

- lib/vix/vips/image.ex
- test/vix/vips/image_test.exs
> Fix issues in handling prefix

- lib/vix/vips/image.ex
- test/vix/vips/image_test.exs
Accept options as string instead of accepting it as string which is error-prone.
Currently string options are still supported but eventually it will be deprecated and removed.
> Make write_to_file and write_to_buffer accept keyword list 

- Makefile
- c_src/Makefile
- lib/vix/vips/foreign.ex
- lib/vix/vips/image.ex
- lib/vix/vips/operation/helper.ex
- test/vix/foreign_test.exs
- test/vix/vips/image_test.exs
> Remove deprecated arguments, improve build system and other minor changes
