c_src/g_object/g_boxed.c
c_src/g_object/g_object.c
c_src/g_object/g_value.c
c_src/g_object/g_value.h
c_src/vips_image.c
c_src/vips_image.h
c_src/vips_operation.c
c_src/vix.c
lib/vix/nif.ex
lib/vix/type.ex
lib/vix/vips/image.ex
test/vix/vips/image_test.exs
test/vix/vips/operation_test.exs

**Other changes**
* correct handling of double value
* add experimental image display (intended to be used with patched livebook)
* change spec for header value - do not wrap return values in tuple

Add write_to_buffer & support different header types

---

lib/vix/vips/image.ex

This was failing for me and I noted the header field was `n-pages` in my tiffs. Checked the [vips documentation](https://www.libvips.org/API/current/libvips-header.html#VIPS-META-N-PAGES:CAPS) and it turns out it's supposed to be a dash, not an underscore. This corrects that so `Vix.Vips.Image.n_pages/1` works as expected.

use correct meta field for n_pages

---

lib/vix/tensor.ex
lib/vix/vips/image.ex
test/vix/vips/image_test.exs

See: #43 
* rebased branch and updated to use zero-copy NIF
* update `Vix.Tensor` to return fixed bit-size

Rebase kipcole9:matrix_interop

---

lib/vix/vips/flag.ex
lib/vix/vips/image.ex
lib/vix/vips/mutable_image.ex
lib/vix/vips/operation.ex

Based upon a request I started working on adding the `draw_*` operations to `MutableImage`. This PR is not ready, but I did want to get your blessing to keep going to flesh out all the functions and add tests. 
I have an experimental `draw` branch of [Image](https://github.com/kipcole9/https://github.com/kipcole9/image/tree/draw) that calls these functions and so far it seems to work very well.  There is a [demo script]( https://github.com/kipcole9/image/blob/draw/bench/add_circles_to_image.exs) that executes in under 500ms to add 1000 circles of a random color and location and uses less than 3Mb of memory.
As always your guidance/corrections most welcome.

Add draw_* operations to MutableImage

---

lib/vix/vips/image.ex
test/support/images.ex
test/test_helper.exs
test/vix/vips/access_test.exs

The PR updates the Access behaviour for images to allow slices in a manner similar to Nx. See the documentation in the `Vix.Vips.Image` module and the tests in the `access_test.exs` files.

Update the Access behaviour to support slices

---

lib/vix/vips/mutable_image.ex
test/vix/vips/mutable_image_test.exs

Adds:
* MutableImage.width/1
* MutableImage.height/1
* MutableImage.bands/1
* MutableImage.has_alpha?/1
When applying the `draw` operations, some of the parameters - like the color - may depend on the number of bands in the image and whether the image has an alpha band. Hence the addition of just the basic image attribute functions for a mutable image.

Add MutableImage attribute access

---

lib/vix/vips/image.ex

Problem: 
- currently path expansion works for the `new_from_file` function, but does not for `write_to_file`
Solution: 
- for symmetry also add path expansion for the `write_to_file` function
Working sample: 
```
{:ok, img} = Image.new_from_file("~/Desktop/kitten.jpg")
hscale = 400 / Image.width(img)
{:ok, resized_img} = Operation.resize(img, hscale)
:ok = Image.write_to_file(resized_img, "~/Desktop/kitten-400x.jpg")
```

Feat: Support `~/..` paths for VIPS.Image.Image.write_to_file

---

README.md

This adds the missing step when compiling using the default compilation mode of VIX_COMPILATION_MODE=PRECOMPILED_NIF_AND_LIBVIPS
Resolves https://github.com/akash-akya/vix/issues/94

Add instruction on generating checksum.exs

---

mix.exs
mix.lock

Hello, thanks for the great library! 
castore package switched from bumping up patch version on 0.1 to 1.0. I checked the diff between 0.1.22 (last version of 0.1 series) and 1.0.0 (first version of 1.0 series), and there are no breaking changes ([link to diff](https://github.com/elixir-mint/castore/compare/v0.1.22...v1.0.0)).
This PR updates `castore` dependency on mix.exs to `~> 1.0`.

Update castore dependency to 1.x

---

lib/vix/vips/mutable_operation.ex
lib/vix/vips/operation.ex
lib/vix/vips/operation_helper.ex
test/vix/vips/operation_test.exs

- Change type of additional output values to map from keyword list
- Skip empty optional argument from function definition when the operation does not have any
Hi @kipcole9! I am making few breaking changes, if possible can you check if this breaks `Image`? 
Btw, I also made few other changes in the master - https://github.com/akash-akya/vix/pull/103. Notably, added limited math operators similar to Image :)

Change additional output type & skip empty optional arguments

---

mix.exs

Trying to run an app on Elixir v1.15.0-rc.0 and OTP 26 that depends on `image` I got the following error downloading https://github.com/akash-akya/sharp-libvips/releases/download/v8.14.2-rc2/libvips-8.14.2-darwin-arm64v8.tar.gz
```
{:error,
{:failed_connect,
[
{:to_address, {~c"github.com", 443}},
{:inet, [:inet],
{:eoptions,
{:undef,
[
{:ssl, :connect,
...
```
I got it working by making sure `:ssl` is included.

Make sure :ssl is available

---

build_scripts/precompiler.exs

I was updating vix on my FreeBSD machine and started debugging why it wasn't building (didn't notice the switch to precompiled libs unless otherwise specified) and while trying to get a valid triple generated for FreeBSD I noticed that this fallback code was incorrect as it was passing the `system_architecture` String through instead of the `current` List.
No other notes, the **VIX_COMPILATION_MODE=PLATFORM_PROVIDED_LIBVIPS** env works fine.

Vix.LibvipsPrecompiled: system_architecture -> current

---

lib/vix/tensor.ex
lib/vix/vips/image.ex
lib/vix/vips/mutable_image.ex
test/vix/vips/image_test.exs

Fixes #126 
Hi @kipcole9, can you check if this breaks something in image?

Fix incorrect image tensor shape

---

lib/vix/vips/image.ex
test/vix/vips/mutable_image_test.exs

* Clarify the acceptable returns from the callback of `Vix.Vips.Image.mutate/2`
* Add retuning the mutated image itself, without decoration, as an acceptable return type. The is helpful with the mutation callback is a pipeline of `!` functions.

Allow returning the mutated image from mutate callback

---

c_src/vips_image.c
c_src/vips_image.h
c_src/vix.c
lib/vix/nif.ex
lib/vix/vips/image.ex
test/vix/nif_test.exs
test/vix/vips/access_test.exs
test/vix/vips/image_test.exs

Added new generic function `write_area_to_binary` which extracts a region to raw binary in a single NIF call as an optimization. 
`write_to_binary`, `write_to_tensor`, `to_list` and others now use this function so there might be slight performance gain. 
`get_pixel` internally just calls `write_area_to_binary` with width & height 1 and returns a 1D list of band values.
```elixir
{:ok, [r, g, b]} = Image.get_pixel(image, 10, 10)
```

Add write_area_to_binary and get_pixel

---

livebooks/auto_correct_rotation.livemd
livebooks/rainbow.livemd
test/vix/vips/access_test.exs

Found via `codespell -S _build,deps,puppies.raw -L bu`

Fix typos again

---

lib/vix/vips/image.ex
test/vix/vips/livebook_render_test.exs

@kipcole9 I am thinking of removing the image metadata tabs while rendering the Image in the livebook and show it below the image instead. 
This is for two reasons:
* Tabs does not seem to play nice other components like `grid`
* I often want to have quick glance over these metadata and want to avoid manually switching tabs on re-evaluate
The changes make it look like this, wdyt?

Change image rendering in Livebook

---

livebooks/introduction.livemd

Introduction Livebook edits

---

c_src/vips_image.c

Fix memory leak in region extraction

---

lib/vix/vips/image.ex
test/vix/vips/image_test.exs

`Vix.Vips.Image.new_from_file/2` now accepts optional keyword list. It still supports path suffix to be backward compatible.
Addresses enhancement mentioned in https://github.com/akash-akya/vix/issues/168#issuecomment-2413024464

Accept image loader options as keyword list

---

lib/vix/operator.ex

Returning boolean is confusing when comparing with multiple bands. Instead of returning boolean, helper function `all?(image, boolean)` is added to easy image comparison and relational operators are updated to return Images

Update relational operators to return image instead of boolean

---

c_src/pipe.c
c_src/vips_foreign.c
c_src/vips_foreign.h
c_src/vix.c
lib/vix/nif.ex
lib/vix/source_pipe.ex
lib/vix/target_pipe.ex
lib/vix/vips/foreign.ex
lib/vix/vips/image.ex
lib/vix/vips/source.ex
lib/vix/vips/target.ex
mix.exs
mix.lock
test/vix/foreign_test.exs
test/vix/vips/image_test.exs
test/vix/vips/operation/helper_test.exs
test/vix/vips/operation_test.exs

* correct dirty IO schedulers
* switch from temp to briefly for generating temp paths in tests
* fix a race-condition in pipe close

Make new_from_enum and write_to_stream accept keyword opts

---

lib/vix/nif.ex

We are exploring lazily loading modules in Elixir to improve compilation times and there was a regression in Vix. This changes ensures forward compatibility without changing the behaviour for previous versions.

Ensure Janitor is always autoloaded

---

.github/workflows/ci.yaml
build_scripts/precompiler.exs
c_src/Makefile
mix.exs
mix.lock

Fixes CI build reliability issues and adds ARM architecture support for precompiled binaries.
- **Fix Mix lock contention**: Use `elixir` directly instead of `mix run`, remove CAStore dependency
- **Add ARM support**: ARM v6/v7 architecture support with QEMU-based CI testing
- **Improve CI reliability**: Add timeouts, caching, better error handling, update actions to v4
- CI workflow improvements and ARM testing job
- Precompiler script made Mix-independent with system CA certificates
- ARM cross-compiler configuration
- Makefile fixes for direct Elixir invocation
Resolves "Waiting for lock on the build directory" errors and enables ARM precompiled binary testing.

Fix CI build issues and add ARM support
